import { Job } from "@/components/jobs/types";

const JOBS: Job[] = [
  {
    id: 1,
    category: "Logistics & Delivery",
    title: "Kwik Delivery Rider",
    employer: "Kwik Nigeria",
    employerInitials: "KW",
    employerColor: "#1D9E75",
    employerBg: "#E1F5EE",
    matchScore: 91,
    location: "Lekki, Lagos",
    arrangement: "In Person",
    arrangementIcon: "ti-map-pin",
    compensationMin: 120000,
    compensationMax: 180000,
    period: "mo",
    description:
      "Join Kwik's fast-growing delivery fleet in Lagos. You'll handle same-day package and food deliveries across Lekki, VI, and Ikoyi. Flexible shifts available — work when you want, earn what you need. Top riders earn bonuses for speed and customer ratings.",
    skills: [
      "Time management",
      "Navigation",
      "Customer service",
      "Physical fitness",
    ],
    equipment: [
      "Motorcycle (or use Kwik's lease)",
      "Smartphone",
      "Helmet & safety gear",
    ],
    startupCost: 85000,
    loanAvailable: true,
    whyMatch: ["High discipline score", "Prefers steady income", "Lagos-based"],
  },
  {
    id: 2,
    category: "Sales & Commerce",
    title: "Jumia Sales Agent",
    employer: "Jumia Nigeria",
    employerInitials: "JU",
    employerColor: "#BA7517",
    employerBg: "#FAEEDA",
    matchScore: 84,
    location: "Nationwide (Remote)",
    arrangement: "Remote",
    arrangementIcon: "ti-wifi",
    compensationMin: 80000,
    compensationMax: 140000,
    period: "mo",
    description:
      "Sell Jumia products to individuals and businesses in your network. You set your own hours and work from anywhere. Commission-based earnings with bonuses for hitting monthly targets. Training and sales materials provided — no prior experience required.",
    skills: [
      "Communication",
      "Persuasion",
      "Social networking",
      "Basic smartphone use",
    ],
    equipment: ["Smartphone", "Data subscription"],
    startupCost: 15000,
    loanAvailable: true,
    whyMatch: [
      "Strong social network signals",
      "Customer service indicators",
      "Nationwide eligible",
    ],
  },
  {
    id: 3,
    category: "Creative & Freelance",
    title: "Graphic Design Freelancer",
    employer: "Verified Clients (Proofident)",
    employerInitials: "PF",
    employerColor: "#534AB7",
    employerBg: "#EEEDFE",
    matchScore: 78,
    location: "Nationwide (Remote)",
    arrangement: "Remote",
    arrangementIcon: "ti-wifi",
    compensationMin: 60000,
    compensationMax: 150000,
    period: "mo",
    description:
      "Get matched with verified SME clients needing logos, social media graphics, flyers, and brand kits. Proofident handles invoicing and payment protection — you just deliver great work. Build your portfolio while earning. Clients are pre-vetted and pay on time.",
    skills: [
      "Adobe Illustrator/Photoshop",
      "Canva Pro",
      "Brand design",
      "Client communication",
    ],
    equipment: ["Laptop (mid-spec or above)", "Adobe Creative Cloud"],
    startupCost: 45000,
    loanAvailable: true,
    whyMatch: [
      "Inferred design skill from purchases",
      "Creative platform usage detected",
      "Independent work pattern",
    ],
  },
  {
    id: 4,
    category: "Transportation",
    title: "Bolt/Uber Driver Partner",
    employer: "Bolt & Uber",
    employerInitials: "BU",
    employerColor: "#185FA5",
    employerBg: "#E6F1FB",
    matchScore: 72,
    location: "Lagos / Abuja",
    arrangement: "In Person",
    arrangementIcon: "ti-map-pin",
    compensationMin: 100000,
    compensationMax: 200000,
    period: "mo",
    description:
      "Drive on Nigeria's top ride-hailing platforms with flexible hours. Peak bonuses during rush hours and weekends. Proofident can connect you to a vehicle lease program so you don't need to own a car. Valid driver's license required.",
    skills: [
      "Valid driver's license",
      "Navigation (Google Maps)",
      "Customer service",
      "Patience",
    ],
    equipment: [
      "Car (own or leased)",
      "Smartphone",
      "Valid license & insurance",
    ],
    startupCost: 200000,
    loanAvailable: true,
    whyMatch: [
      "Lagos location match",
      "Behavioral discipline score",
      "Consistent income pattern",
    ],
  },
  {
    id: 5,
    category: "Tech & Digital",
    title: "Remote Junior Developer",
    employer: "Multiple Startups",
    employerInitials: "ST",
    employerColor: "#3C3489",
    employerBg: "#EEEDFE",
    matchScore: 68,
    location: "Fully Remote",
    arrangement: "Remote",
    arrangementIcon: "ti-wifi",
    compensationMin: 150000,
    compensationMax: 350000,
    period: "mo",
    description:
      "Contract and full-time junior dev roles at Nigerian and international startups. Stacks vary: React, Node.js, Python, mobile (Flutter/React Native). Proofident pre-verifies your skills via a short coding assessment so employers skip straight to interviews. Higher credit score unlocks senior roles.",
    skills: [
      "JavaScript / Python",
      "Git & version control",
      "Problem solving",
      "API integration",
    ],
    equipment: ["Laptop", "Stable internet connection"],
    startupCost: 0,
    loanAvailable: false,
    whyMatch: [
      "CS degree signal detected",
      "High data usage on coding platforms",
      "Remote-ready profile",
    ],
  },
];

export { JOBS };
