const NEXT_PUBLIC_MONO_PUBLIC_KEY = process.env.NEXT_PUBLIC_MONO_PUBLIC_KEY;
const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL

export { 
  NEXT_PUBLIC_MONO_PUBLIC_KEY,
  NEXT_PUBLIC_API_URL
}